import type { Metadata } from "next";
import "./globals.css";
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";

export const metadata: Metadata = {
  title: "Portifólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="font-kanit flex flex-col min-h-screen justify-between">
        <Cabecalho />
        <main className="flex-grow">
          {children}
        </main>
        <Rodape />
      </body>
    </html>
  );
}